### ISSUE TITLE
Just chat about the client

### ISSUE THREAD

**Issue by wijiler** [Wijhack/Wijhack#1]
client chat

**Comment by Pinary-Pi** [comment]
@wijiler what is this?

**Comment by wijiler** [comment]
idk personal hack client and also will be posting some of my mods im working on here

**Comment by Pinary-Pi** [comment]
> idk personal hack client and also will be posting some of my mods im working on here

Cool, what types of mods do you have planned?

**Comment by wijiler** [comment]
> > idk personal hack client and also will be posting some of my mods im working on here
> 
> Cool, what types of mods do you have planned?

just whatever i would like

**Comment by EliteUn17y** [comment]
need help with mixins?

**Comment by wijiler** [comment]
just wanna know what they do

**Comment by EliteUn17y** [comment]
![image](https://user-images.githubusercontent.com/68102994/123479615-1a50ad80-d5f9-11eb-8987-aee13b8b8d9d.png)
its this basically

**Comment by EliteUn17y** [comment]
they let you change the games code from a mod

**Comment by wijiler** [comment]
ahh

**Comment by wijiler** [comment]
ty

**Comment by EliteUn17y** [comment]
np

**Comment by wijiler** [comment]
very useful

**Comment by wijiler** [comment]
> np

wait wtf org.lwjgl isnt recognized

**Comment by wijiler** [comment]
think I fricked sum up

**Comment by wijiler** [comment]
thanks again for the help

**Comment by EliteUn17y** [comment]
np

**Comment by wijiler** [comment]
frickkkkkkkkkkkkkkkkkkkkkkkk

**Comment by wijiler** [comment]
i have no idea how to setup mixins because all the tutorials are using fricking gradle 2 and im on gradle 7 and this crap dont work

**Comment by wijiler** [comment]
well wijhack is done now im too stressed and its falling apart and i cant do anything about it and no this time not a mixin issue
